import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="w-screen h-screen bg-slate-500 flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Content</p>
      </main>
    </div>
  );
}
